# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter

name: Lint Code Base

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Step 3: Install dotnet-format
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format --version latest --ignore-failed-sources

      # Step 4: Auto-fix formatting issues
      - name: Auto-fix formatting
        run: dotnet format --folder . --verbosity diagnostic
        env:
          DOTNET_ROOT: /usr/share/dotnet

      # Step 5: Run linter (optional step)
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
